apiVersion: v1
kind: Service
metadata:
  name: frontend-nginxapp-nodeport-servise
  labels: 
    app: frontend-nginxapp
    tier: fronend
spec:
  type: NodePort
  selector:
    app: frontend-nginxapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31234
