apiVersion: app/v1
kind: Deployment
metadata:
  name: user-management-microservice
  labels: 
    app: user-management-restapp
  namespace: dev3
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: user-management-restapp
  template:
    metadata:
      labels:
        app: user-management-restapp
    spec:
      initContainers: 
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: user-management-restapp
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          ports:
            - containerPort: 8095
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USERNAME
              value: "root"            
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password 
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nz -z localhost:8095
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /usermgmt/health-status
              port: 8095
            initialDelaySeconds: 60
            periodSeconds: 10      