apiVersion: v1
kind: Service   
metadata:
  name: user-management-service
  labels:
    app: user-management-restapp
  namespace: dev3
spec:
  type: NodePort
  selector: 
    app: user-management-restapp
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 30095